apiVersion: apps/v1
kind: Deployment
metadata:
  name: stakater-frontend
spec:
  selector:
    matchLabels:
      app: stakater-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: stakater-frontend
    spec:
      containers:
        - name: stakater-frontend
          image: nayan2512/stakater-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: stakater-frontend-service
spec:
  selector:
    app: stakater-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
  type: NodePort
