replicaCount: 1
image:
  repository: "docker.io/nayan2512/stakater-backend"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  timeoutSeconds: 5
  periodSeconds: 15
  protocol : TCP

environment:
  name: Nayan
